//#include "cubeClass.h"
////scramble
//void Scramble(int cube[][3][3], int N)
//{
//	cout << "------------------------SCRAMBLE-------------------------\n";
//	switch (N)
//	{
//	case 0:
//		F(cube);
//		U(cube);
//		B(cube, 2);
//		F(cube, 2);
//		L(cube, 2);
//		U(cube);
//		L(cube);
//		B(cube, 2);
//		F(cube);
//		L(cube, 2);
//		F(cube);
//		Ri(cube);
//		U(cube, 2);
//		L(cube, 2);
//		R(cube, 2);
//		Fi(cube);
//		U(cube);
//		L(cube, 2);
//		F(cube, 2);
//		Di(cube);
//		B(cube);
//		Di(cube);
//		U(cube);
//		F(cube, 2);
//		L(cube, 2);
//		F(cube);
//		L(cube);
//		Bi(cube);
//		U(cube, 2);
//		F(cube);
//		break;
//	case 1:
//		Di(cube);
//		Ri(cube);
//		Fi(cube);
//		Di(cube);
//		Ri(cube);
//		D(cube);
//		B(cube, 2);
//		L(cube);
//		D(cube);
//		B(cube);
//		L(cube);
//		F(cube, 2);
//		R(cube, 2);
//		D(cube);
//		Bi(cube);
//		R(cube);
//		D(cube);
//		U(cube, 2);
//		L(cube, 2);
//		F(cube);
//		Li(cube);
//		R(cube, 2);
//		Ui(cube);
//		R(cube, 2);
//		Bi(cube);
//		Ri(cube);
//		Ui(cube);
//		L(cube);
//		B(cube, 2);
//		F(cube, 2);
//		break;
//	case 2:
//		F(cube);
//		R(cube, 2);
//		Fi(cube);
//		Li(cube);
//		D(cube);
//		Fi(cube);
//		U(cube, 2);
//		B(cube);
//		F(cube, 2);
//		D(cube);
//		U(cube, 2);
//		L(cube);
//		U(cube);
//		Bi(cube);
//		Fi(cube);
//		D(cube);
//		Ui(cube);
//		B(cube, 2);
//		F(cube, 2);
//		D(cube, 2);
//		Ri(cube);
//		F(cube, 2);
//		D(cube);
//		Li(cube);
//		B(cube);
//		F(cube, 2);
//		L(cube);
//		Ri(cube);
//		F(cube, 2);
//		Ri(cube);
//		break;
//
//	case 3:
//		B(cube, 2);
//		D(cube);
//		U(cube, 2);
//		B(cube, 2);
//		F(cube, 2);
//		Ui(cube);
//		Bi(cube);
//		U(cube);
//		B(cube);
//		R(cube);
//		F(cube, 2);
//		Ui(cube);
//		Bi(cube);
//		Ri(cube);
//		B(cube, 2);
//		D(cube);
//		L(cube, 2);
//		B(cube, 2);
//		Ui(cube);
//		L(cube, 2);
//		R(cube);
//		D(cube);
//		R(cube);
//		Bi(cube);
//		Ui(cube);
//		L(cube);
//		R(cube);
//		Bi(cube);
//		L(cube, 2);
//		B(cube);
//		break;
//	case 4:
//		R(cube, 2);
//		D(cube);
//		U(cube);
//		R(cube, 2);
//		D(cube, 2);
//		Li(cube);
//		Ri(cube);
//		D(cube);
//		U(cube);
//		F(cube);
//		L(cube);
//		R(cube);
//		Fi(cube);
//		L(cube);
//		Ri(cube);
//		Bi(cube);
//		Fi(cube);
//		R(cube);
//		F(cube);
//		D(cube);
//		U(cube, 2);
//		L(cube);
//		Ri(cube);
//		Bi(cube);
//		F(cube, 2);
//		L(cube);
//		D(cube, 2);
//		U(cube);
//		Bi(cube);
//		Li(cube);
//		break;
//	case 5:
//		F(cube);
//		U(cube, 2);
//		Bi(cube);
//		Li(cube);
//		Fi(cube);
//		R(cube);
//		B(cube, 2);
//		Di(cube);
//		U(cube, 2);
//		Ri(cube);
//		U(cube, 2);
//		R(cube, 2);
//		B(cube);
//		R(cube, 2);
//		Di(cube);
//		U(cube);
//		B(cube);
//		R(cube);
//		D(cube, 2);
//		U(cube);
//		L(cube, 2);
//		R(cube, 2);
//		D(cube);
//		Li(cube);
//		F(cube);
//		R(cube);
//		Bi(cube);
//		F(cube, 2);
//		L(cube);
//		B(cube);
//		break;
//	case 6:
//		L(cube, 2);
//		B(cube, 2);
//		Fi(cube);
//		L(cube);
//		D(cube);
//		B(cube, 2);
//		Ri(cube);
//		Bi(cube);
//		D(cube);
//		B(cube, 2);
//		L(cube, 2);
//		Ri(cube);
//		D(cube, 2);
//		Fi(cube);
//		U(cube, 2);
//		L(cube, 2);
//		B(cube);
//		U(cube);
//		L(cube, 2);
//		U(cube);
//		Ri(cube);
//		Ui(cube);
//		Fi(cube);
//		Li(cube);
//		Bi(cube);
//		D(cube, 2);
//		U(cube, 2);
//		F(cube, 2);
//		D(cube);
//		R(cube);
//		break;
//	case 7:
//		U(cube);
//		F(cube);
//		Di(cube);
//		Fi(cube);
//		Ui(cube);
//		Fi(cube);
//		U(cube);
//		R(cube, 2);
//		F(cube);
//		R(cube);
//		B(cube, 2);
//		D(cube);
//		U(cube, 2);
//		B(cube, 2);
//		Li(cube);
//		B(cube, 2);
//		R(cube, 2);
//		B(cube, 2);
//		U(cube);
//		Li(cube);
//		D(cube);
//		B(cube);
//		L(cube, 2);
//		Ui(cube);
//		B(cube, 2);
//		R(cube);
//		Di(cube);
//		U(cube, 2);
//		Fi(cube);
//		Ui(cube);
//		break;
//	case 8:
//		F(cube, 2);
//		Di(cube);
//		U(cube, 2);
//		B(cube);
//		U(cube);
//		B(cube, 2);
//		F(cube, 2);
//		L(cube, 2);
//		B(cube, 2);
//		L(cube);
//		F(cube, 2);
//		L(cube, 2);
//		B(cube, 2);
//		L(cube);
//		D(cube, 2);
//		U(cube);
//		B(cube, 2);
//		D(cube);
//		F(cube);
//		D(cube, 2);
//		Ri(cube);
//		F(cube);
//		L(cube, 2);
//		Bi(cube);
//		Ui(cube);
//		B(cube);
//		L(cube);
//		R(cube, 2);
//		Di(cube);
//		L(cube);
//		break;
//	case 9:
//		D(cube);
//		Ri(cube);
//		Bi(cube);
//		L(cube, 2);
//		D(cube, 2);
//		U(cube, 2);
//		Li(cube);
//		U(cube, 2);
//		R(cube, 2);
//		Fi(cube);
//		D(cube, 2);
//		F(cube);
//		L(cube, 2);
//		Di(cube);
//		Ui(cube);
//		Ri(cube);
//		B(cube, 2);
//		Fi(cube);
//		Ri(cube);
//		Fi(cube);
//		L(cube, 2);
//		Ri(cube);
//		Di(cube);
//		Ui(cube);
//		Ri(cube);
//		Ui(cube);
//		R(cube);
//		Bi(cube);
//		D(cube);
//		F(cube, 2);
//		break;
//	case 10:
//		B(cube, 2);
//		Li(cube);
//		R(cube);
//		B(cube, 2);
//		Li(cube);
//		R(cube);
//		Di(cube);
//		F(cube);
//		Di(cube);
//		Li(cube);
//		R(cube, 2);
//		D(cube, 2);
//		Bi(cube);
//		Ui(cube);
//		R(cube);
//		Ui(cube);
//		B(cube);
//		F(cube, 2);
//		L(cube, 2);
//		U(cube);
//		B(cube, 2);
//		Ui(cube);
//		B(cube, 2);
//		D(cube);
//		F(cube, 2);
//		R(cube, 2);
//		F(cube);
//		U(cube);
//		F(cube, 2);
//		R(cube, 2);
//		break;
//	case 11:
//		L(cube);
//		R(cube, 2);
//		Bi(cube);
//		L(cube);
//		F(cube, 2);
//		U(cube, 2);
//		L(cube);
//		F(cube);
//		D(cube, 2);
//		Ui(cube);
//		Ri(cube);
//		B(cube);
//		Ui(cube);
//		Ri(cube);
//		Ui(cube);
//		B(cube);
//		D(cube, 2);
//		Li(cube);
//		Di(cube);
//		U(cube, 2);
//		L(cube, 2);
//		Fi(cube);
//		Li(cube);
//		B(cube);
//		Fi(cube);
//		D(cube);
//		Li(cube);
//		B(cube);
//		F(cube, 2);
//		R(cube);
//		break;
//	case 12:
//		L(cube);
//		Ui(cube);
//		F(cube, 2);
//		L(cube, 2);
//		Ui(cube);
//		L(cube);
//		U(cube);
//		L(cube);
//		Di(cube);
//		B(cube);
//		Fi(cube);
//		Ri(cube);
//		U(cube);
//		Li(cube);
//		Ri(cube);
//		F(cube);
//		D(cube, 2);
//		Ri(cube);
//		U(cube, 2);
//		L(cube, 2);
//		F(cube);
//		Li(cube);
//		R(cube);
//		B(cube, 2);
//		F(cube);
//		Ui(cube);
//		Ri(cube);
//		Fi(cube);
//		R(cube, 2);
//		D(cube);
//		break;
//	case 13:
//		Ri(cube);
//		B(cube);
//		D(cube);
//		F(cube);
//		L(cube);
//		R(cube);
//		Bi(cube);
//		Ri(cube);
//		Bi(cube);
//		Ui(cube);
//		Ri(cube);
//		Bi(cube);
//		Fi(cube);
//		Ui(cube);
//		B(cube);
//		U(cube);
//		L(cube, 2);
//		F(cube);
//		Ui(cube);
//		L(cube);
//		R(cube, 2);
//		B(cube);
//		D(cube);
//		U(cube);
//		Ri(cube);
//		U(cube);
//		F(cube, 2);
//		D(cube);
//		U(cube, 2);
//		L(cube);
//		break;
//	case 14:
//		Li(cube);
//		Di(cube);
//		U(cube, 2);
//		R(cube, 2);
//		Fi(cube);
//		Ri(cube);
//		Ui(cube);
//		B(cube);
//		F(cube, 2);
//		R(cube, 2);
//		F(cube, 2);
//		L(cube, 2);
//		B(cube);
//		F(cube);
//		L(cube);
//		U(cube, 2);
//		Li(cube);
//		D(cube, 2);
//		Ri(cube);
//		U(cube, 2);
//		Fi(cube);
//		L(cube, 2);
//		Ri(cube);
//		Bi(cube);
//		Fi(cube);
//		L(cube, 2);
//		R(cube, 2);
//		Fi(cube);
//		Di(cube);
//		U(cube, 2);
//		break;
//	case 15:
//		R(cube);
//		F(cube, 2);
//		U(cube, 2);
//		B(cube);
//		F(cube, 2);
//		U(cube, 2);
//		R(cube, 2);
//		U(cube);
//		L(cube);
//		U(cube, 2);
//		F(cube, 2);
//		R(cube, 2);
//		B(cube);
//		Fi(cube);
//		Ri(cube);
//		Di(cube);
//		L(cube);
//		F(cube);
//		L(cube, 2);
//		Di(cube);
//		U(cube, 2);
//		Bi(cube);
//		U(cube, 2);
//		Li(cube);
//		Ri(cube);
//		Di(cube);
//		R(cube, 2);
//		Fi(cube);
//		L(cube, 2);
//		D(cube, 2);
//		break;
//	case 16:
//		Fi(cube);
//		R(cube, 2);
//		D(cube, 2);
//		Ui(cube);
//		F(cube, 2);
//		Ui(cube);
//		L(cube, 2);
//		F(cube);
//		D(cube, 2);
//		L(cube);
//		R(cube, 2);
//		U(cube, 2);
//		L(cube);
//		R(cube, 2);
//		D(cube);
//		Ui(cube);
//		Ri(cube);
//		B(cube, 2);
//		Ri(cube);
//		U(cube, 2);
//		B(cube, 2);
//		Ri(cube);
//		U(cube, 2);
//		Li(cube);
//		Bi(cube);
//		Li(cube);
//		B(cube);
//		F(cube, 2);
//		D(cube);
//		F(cube);
//		break;
//	case 17:
//		L(cube, 2);
//		R(cube);
//		D(cube);
//		F(cube, 2);
//		Di(cube);
//		U(cube, 2);
//		F(cube);
//		Li(cube);
//		Fi(cube);
//		R(cube);
//		Di(cube);
//		B(cube);
//		L(cube, 2);
//		R(cube, 2);
//		U(cube, 2);
//		B(cube);
//		Fi(cube);
//		L(cube, 2);
//		F(cube);
//		D(cube);
//		B(cube, 2);
//		Fi(cube);
//		L(cube, 2);
//		Di(cube);
//		F(cube, 2);
//		Di(cube);
//		B(cube, 2);
//		F(cube, 2);
//		D(cube);
//		U(cube);
//		break;
//	case 18:
//		D(cube);
//		L(cube);
//		R(cube, 2);
//		Ui(cube);
//		L(cube);
//		B(cube);
//		U(cube);
//		Fi(cube);
//		Li(cube);
//		Fi(cube);
//		Li(cube);
//		D(cube);
//		Li(cube);
//		R(cube, 2);
//		Di(cube);
//		U(cube);
//		L(cube, 2);
//		R(cube, 2);
//		D(cube);
//		U(cube);
//		B(cube);
//		Li(cube);
//		Ri(cube);
//		D(cube);
//		R(cube, 2);
//		Ui(cube);
//		F(cube);
//		Ri(cube);
//		Ui(cube);
//		Ri(cube);
//		break;
//	case 19:
//		Ri(cube);
//		F(cube);
//		L(cube, 2);
//		U(cube, 2);
//		Bi(cube);
//		Ri(cube);
//		Bi(cube);
//		F(cube, 2);
//		Ui(cube);
//		L(cube);
//		R(cube);
//		D(cube);
//		Ri(cube);
//		U(cube, 2);
//		Ri(cube);
//		U(cube);
//		B(cube);
//		Di(cube);
//		Fi(cube);
//		Di(cube);
//		Fi(cube);
//		R(cube);
//		Di(cube);
//		Bi(cube);
//		D(cube, 2);
//		R(cube, 2);
//		B(cube);
//		Li(cube);
//		Ui(cube);
//		R(cube, 2);
//		break;
//	case 20:
//		U(cube, 2);
//		B(cube, 2);
//		F(cube, 2);
//		D(cube);
//		F(cube, 2);
//		D(cube, 2);
//		Fi(cube);
//		Di(cube);
//		U(cube);
//		L(cube, 2);
//		D(cube, 2);
//		L(cube, 2);
//		U(cube);
//		Ri(cube);
//		F(cube, 2);
//		R(cube, 2);
//		B(cube, 2);
//		U(cube, 2);
//		Fi(cube);
//		U(cube, 2);
//		L(cube, 2);
//		R(cube, 2);
//		Bi(cube);
//		D(cube, 2);
//		B(cube);
//		L(cube);
//		R(cube, 2);
//		D(cube, 2);
//		Li(cube);
//		Bi(cube);
//		break;
//	case 21:
//		Di(cube);
//		Bi(cube);
//		R(cube, 2);
//		U(cube, 2);
//		F(cube, 2);
//		L(cube, 2);
//		Ri(cube);
//		U(cube);
//		Li(cube);
//		R(cube);
//		Di(cube);
//		U(cube, 2);
//		L(cube, 2);
//		Di(cube);
//		F(cube);
//		D(cube, 2);
//		U(cube);
//		R(cube);
//		Di(cube);
//		U(cube, 2);
//		Fi(cube);
//		Li(cube);
//		Ri(cube);
//		U(cube);
//		Fi(cube);
//		L(cube);
//		Fi(cube);
//		Di(cube);
//		Fi(cube); R(cube, 2);
//		break;
//	case 22:
//		U(cube, 2);
//		R(cube);
//		Bi(cube);
//		L(cube, 2);
//		B(cube, 2);
//		F(cube);
//		L(cube, 2);
//		B(cube, 2);
//		F(cube, 2);
//		L(cube, 2);
//		R(cube);
//		Bi(cube);
//		F(cube);
//		Di(cube);
//		R(cube, 2);
//		U(cube, 2);
//		Bi(cube);
//		Ri(cube);
//		D(cube);
//		L(cube, 2);
//		Fi(cube);
//		Ui(cube);
//		R(cube);
//		D(cube, 2);
//		B(cube);
//		L(cube);
//		Ri(cube);
//		B(cube, 2);
//		U(cube);
//		R(cube);
//		break;
//	case 23:
//		L(cube);
//		Fi(cube);
//		D(cube, 2);
//		Ui(cube);
//		Li(cube);
//		U(cube, 2);
//		Li(cube);
//		D(cube);
//		Li(cube);
//		B(cube, 2);
//		F(cube, 2);
//		Di(cube);
//		U(cube, 2);
//		B(cube);
//		L(cube);
//		F(cube, 2);
//		R(cube, 2);
//		U(cube);
//		Ri(cube);
//		U(cube);
//		L(cube);
//		Bi(cube);
//		Li(cube);
//		R(cube);
//		Ui(cube);
//		L(cube, 2);
//		D(cube);
//		Ui(cube);
//		L(cube);
//		Ri(cube);
//		break;
//	case 24:
//		Fi(cube);
//		D(cube, 2);
//		L(cube);
//		R(cube);
//		D(cube, 2);
//		R(cube, 2);
//		U(cube);
//		B(cube, 2);
//		D(cube, 2);
//		U(cube, 2);
//		B(cube, 2);
//		R(cube, 2);
//		D(cube);
//		Ui(cube);
//		L(cube);
//		B(cube);
//		D(cube);
//		Fi(cube);
//		Di(cube);
//		Li(cube);
//		R(cube);
//		U(cube);
//		F(cube);
//		R(cube, 2);
//		D(cube, 2);
//		B(cube);
//		F(cube, 2);
//		U(cube, 2);
//		R(cube);
//		Di(cube);
//		break;
//	case 25:
//		F(cube);
//		Ui(cube);
//		Bi(cube);
//		F(cube);
//		D(cube, 2);
//		B(cube, 2);
//		Fi(cube);
//		U(cube, 2);
//		Li(cube);
//		F(cube, 2);
//		L(cube, 2);
//		D(cube, 2);
//		R(cube);
//		Di(cube);
//		Ui(cube);
//		Li(cube);
//		R(cube);
//		B(cube);
//		Fi(cube);
//		L(cube);
//		B(cube, 2);
//		F(cube);
//		L(cube);
//		Ui(cube);
//		Li(cube);
//		B(cube, 2);
//		L(cube, 2);
//		B(cube, 2);
//		Di(cube);
//		L(cube);
//		break;
//	case 26:
//		D(cube);
//		L(cube);
//		R(cube, 2);
//		Di(cube);
//		L(cube, 2);
//		Di(cube);
//		F(cube, 2);
//		Di(cube);
//		Bi(cube);
//		U(cube);
//		L(cube);
//		U(cube);
//		R(cube, 2);
//		Ui(cube);
//		F(cube);
//		Li(cube);
//		B(cube, 2);
//		L(cube);
//		D(cube);
//		B(cube, 2);
//		R(cube, 2);
//		B(cube);
//		F(cube, 2);
//		Ri(cube);
//		F(cube, 2);
//		Ui(cube);
//		F(cube, 2);
//		D(cube);
//		Ui(cube);
//		B(cube);
//		break;
//	case 27:
//		D(cube, 2);
//		F(cube);
//		Li(cube);
//		Fi(cube);
//		D(cube);
//		Ri(cube);
//		F(cube, 2);
//		R(cube);
//		F(cube);
//		D(cube);
//		Ui(cube);
//		Li(cube);
//		Bi(cube);
//		L(cube);
//		Di(cube);
//		B(cube, 2);
//		Ui(cube);
//		R(cube, 2);
//		D(cube);
//		B(cube);
//		L(cube, 2);
//		D(cube, 2);
//		Li(cube);
//		B(cube);
//		D(cube);
//		U(cube, 2);
//		R(cube, 2);
//		D(cube, 2);
//		Bi(cube);
//		F(cube, 2);
//		break;
//	case 28:
//		D(cube);
//		F(cube, 2);
//		D(cube, 2);
//		Fi(cube);
//		D(cube, 2);
//		B(cube, 2);
//		D(cube, 2);
//		U(cube);
//		L(cube);
//		Fi(cube);
//		L(cube);
//		Ri(cube);
//		B(cube);
//		U(cube, 2);
//		B(cube, 2);
//		F(cube, 2);
//		D(cube, 2);
//		F(cube);
//		D(cube);
//		Fi(cube);
//		L(cube, 2);
//		B(cube);
//		D(cube);
//		U(cube, 2);
//		B(cube, 2);
//		U(cube);
//		F(cube, 2);
//		D(cube, 2);
//		Ui(cube);
//		R(cube, 2);
//		break;
//	case 29:
//		Fi(cube);
//		U(cube);
//		L(cube);
//		Fi(cube);
//		Ui(cube);
//		R(cube);
//		Fi(cube);
//		Ri(cube);
//		D(cube, 2);
//		Fi(cube);
//		L(cube);
//		Bi(cube);
//		U(cube, 2);
//		L(cube);
//		R(cube, 2);
//		Fi(cube);
//		R(cube, 2);
//		D(cube);
//		Ui(cube);
//		Li(cube);
//		B(cube, 2);
//		F(cube);
//		L(cube);
//		D(cube);
//		F(cube, 2);
//		Di(cube);
//		L(cube, 2);
//		U(cube);
//		B(cube);
//		Fi(cube);
//		break;
//	case 30:
//		Li(cube);
//		R(cube, 2);
//		F(cube);
//		U(cube, 2);
//		R(cube);
//		Fi(cube);
//		L(cube);
//		R(cube, 2);
//		Bi(cube);
//		F(cube, 2);
//		Ri(cube);
//		F(cube, 2);
//		Ri(cube);
//		B(cube, 2);
//		R(cube, 2);
//		Ui(cube);
//		L(cube, 2);
//		R(cube, 2);
//		Di(cube);
//		Fi(cube);
//		Li(cube);
//		F(cube, 2);
//		U(cube);
//		Fi(cube);
//		Di(cube);
//		Fi(cube);
//		R(cube, 2);
//		B(cube);
//		R(cube, 2);
//		Di(cube);
//		break;
//	case 31:
//		Di(cube);
//		U(cube, 2);
//		B(cube);
//		F(cube);
//		Li(cube);
//		R(cube);
//		F(cube, 2);
//		Di(cube);
//		F(cube, 2);
//		U(cube);
//		B(cube);
//		U(cube);
//		Bi(cube);
//		L(cube);
//		Ui(cube);
//		F(cube, 2);
//		Di(cube);
//		U(cube);
//		Li(cube);
//		B(cube);
//		F(cube, 2);
//		L(cube, 2);
//		R(cube, 2);
//		Di(cube);
//		L(cube);
//		R(cube, 2);
//		D(cube, 2);
//		Ui(cube);
//		F(cube);
//		D(cube);
//		break;
//	case 32:
//		Li(cube);
//		Ui(cube);
//		L(cube, 2);
//		F(cube);
//		L(cube, 2);
//		F(cube, 2);
//		Li(cube);
//		Bi(cube);
//		F(cube);
//		Li(cube);
//		Bi(cube);
//		D(cube);
//		Ui(cube);
//		F(cube);
//		D(cube, 2);
//		F(cube, 2);
//		U(cube);
//		R(cube, 2);
//		D(cube); Bi(cube);
//		R(cube);
//		Ui(cube);
//		B(cube, 2);
//		D(cube, 2);
//		U(cube);
//		B(cube, 2);
//		L(cube, 2);
//		Bi(cube);
//		D(cube);
//		Ui(cube);
//		break;
//	case 33:
//		Di(cube);
//		Fi(cube);
//		U(cube, 2);
//		Fi(cube);
//		Di(cube);
//		U(cube);
//		L(cube);
//		F(cube);
//		Li(cube);
//		U(cube);
//		R(cube);
//		U(cube, 2);
//		L(cube, 2);
//		D(cube);
//		U(cube);
//		B(cube);
//		Ri(cube);
//		Di(cube);
//		Ui(cube);
//		R(cube);
//		Fi(cube);
//		D(cube, 2);
//		B(cube, 2);
//		F(cube);
//		Li(cube);
//		Bi(cube);
//		L(cube, 2);
//		D(cube, 2);
//		Ui(cube);
//		R(cube, 2);
//		break;
//	case 34:
//		Ui(cube);
//		Bi(cube);
//		L(cube, 2);
//		Bi(cube);
//		R(cube);
//		Di(cube);
//		B(cube);
//		Li(cube);
//		D(cube, 2);
//		U(cube);
//		Ri(cube);
//		Di(cube); F(cube);
//		Di(cube); U(cube, 2);
//		Li(cube);
//		B(cube, 2);
//		Fi(cube);
//		L(cube);
//		R(cube, 2);
//		B(cube, 2);
//		L(cube, 2);
//		B(cube, 2);
//		Ui(cube);
//		Li(cube);
//		B(cube, 2);
//		F(cube);
//		L(cube, 2);
//		D(cube);
//		L(cube);
//		break;
//	case 35:
//		L(cube);
//		R(cube, 2);
//		Ui(cube);
//		Fi(cube);
//		R(cube, 2);
//		B(cube, 2);
//		R(cube);
//		F(cube, 2);
//		L(cube, 2);
//		Ui(cube);
//		L(cube);
//		Di(cube);
//		F(cube);
//		Li(cube);
//		Fi(cube);
//		Ri(cube);
//		Bi(cube);
//		F(cube, 2);
//		R(cube);
//		Bi(cube);
//		U(cube, 2);
//		L(cube, 2);
//		Di(cube);
//		L(cube);
//		U(cube);
//		Ri(cube);
//		Di(cube);
//		Ri(cube);
//		Di(cube);
//		Ui(cube);
//		break;
//	case 36:
//		R(cube);
//		B(cube, 2);
//		L(cube, 2);
//		D(cube);
//		F(cube, 2);
//		Ui(cube);
//		Li(cube);
//		Ri(cube);
//		B(cube, 2);
//		R(cube);
//		D(cube);
//		F(cube, 2);
//		R(cube, 2);
//		B(cube);
//		R(cube, 2);
//		D(cube);
//		L(cube, 2);
//		Ui(cube);
//		B(cube, 2);
//		Li(cube);
//		D(cube);
//		F(cube, 2);
//		U(cube);
//		R(cube, 2);
//		Fi(cube);
//		D(cube, 2);
//		B(cube);
//		Ui(cube);
//		L(cube);
//		Ri(cube);
//		break;
//	case 37:
//		Ui(cube);
//		F(cube, 2);
//		U(cube);
//		Li(cube);
//		R(cube);
//		Fi(cube);
//		L(cube);
//		Ui(cube);
//		B(cube);
//		Fi(cube);
//		U(cube, 2);
//		Li(cube);
//		D(cube, 2);
//		F(cube);
//		Ui(cube);
//		B(cube, 2);
//		L(cube);
//		Di(cube);
//		U(cube, 2);
//		R(cube, 2);
//		F(cube, 2);
//		Li(cube);
//		Ri(cube);
//		F(cube, 2);
//		Li(cube);
//		Fi(cube);
//		D(cube, 2);
//		B(cube);
//		R(cube);
//		D(cube);
//		break;
//	case 38:
//		L(cube, 2);
//		D(cube);
//		U(cube, 2);
//		L(cube, 2);
//		R(cube);
//		Di(cube);
//		Fi(cube);
//		D(cube, 2);
//		L(cube);
//		Ri(cube);
//		D(cube, 2);
//		U(cube);
//		L(cube, 2);
//		D(cube);
//		U(cube, 2);
//		F(cube);
//		Ui(cube);
//		R(cube, 2);
//		U(cube);
//		F(cube, 2);
//		Di(cube);
//		Ri(cube);
//		Ui(cube);
//		Bi(cube);
//		Fi(cube);
//		L(cube);
//		R(cube);
//		Bi(cube);
//		L(cube, 2);
//		Di(cube);
//		break;
//	case 39:
//		Fi(cube);
//		U(cube);
//		L(cube, 2);
//		B(cube);
//		D(cube);
//		U(cube);
//		F(cube, 2);
//		Di(cube);
//		L(cube, 2);
//		B(cube, 2);
//		D(cube);
//		B(cube, 2);
//		U(cube);
//		B(cube, 2);
//		Fi(cube);
//		D(cube, 2);
//		L(cube, 2);
//		Bi(cube);
//		F(cube, 2);
//		D(cube, 2);
//		Fi(cube);
//		D(cube);
//		B(cube);
//		L(cube, 2);
//		U(cube, 2);
//		B(cube, 2);
//		L(cube);
//		Fi(cube);
//		D(cube, 2);
//		Bi(cube);
//		break;
//
//	}
//	StampaM(cube);
//	cout << "------------------------SCRAMBLE-------------------------\n";
//}